Repository moul/sgtm, pull requests merged in 2020-11, with the labels that each got.

#50 feat: multi-admins
  api/sgtm.proto
  cmd/sgtm/depaware.txt
  gen.sum
  go.mod
  go.sum
  pkg/sgtm/templates.go
  pkg/sgtmpb/sgtm.pb.go
  rules.mk
Labels: enhancement, 🔍 Ready for Review

#53 chore: switch to isolated code generation
  AUTHORS
  Makefile
  gen.sum
  go.mod
  go.sum
  pkg/sgtm/service.go
  pkg/sgtmpb/sgtm.pb.go
  pkg/sgtmpb/sgtm.pb.gw.go
  pkg/sgtmpb/sgtm_grpc.pb.go
  rules.mk
  tool/docker-protoc/Dockerfile
  tool/docker-protoc/Makefile
Labels: chore, 🔍 Ready for Review

#49 upload via ipfs
  .dockerignore
  .gitignore
  Dockerfile.fast
  Makefile
  api/sgtm.proto
  cmd/sgtm/main.go
  deployments/.gitignore
  deployments/sgtm.club/config.example.txt
  deployments/sgtm.club/docker-compose.yml
  gen.sum
  pkg/sgtm/http_server.go
  pkg/sgtm/ipfs.go
  pkg/sgtm/opts.go
  pkg/sgtm/page_new.go
  pkg/sgtm/page_new.tmpl.html
  pkg/sgtm/page_post-edit.tmpl.html
  pkg/sgtm/page_post.go
  pkg/sgtm/page_post.tmpl.html
  pkg/sgtm/processing.go
  pkg/sgtm/service.go
  pkg/sgtmpb/helpers.go
  pkg/sgtmpb/sgtm.pb.go
Labels: 🔍 Ready for Review

#56 fix: use http.ServeContent for post/download endpoint
  pkg/sgtm/ipfs.go
  pkg/sgtm/page_post.go
  pkg/sgtm/processing.go
Labels: bug, ✅ Approved

#55 feat: support emojis
  AUTHORS
  go.mod
  go.sum
  pkg/sgtm/page_post.tmpl.html
  pkg/sgtm/templates.go
  static/_assets/js/script.js
Labels: enhancement, ✅ Approved

#57 feat: add ipfs fallback gateways in audio tag
  pkg/sgtm/ipfs.go
  pkg/sgtm/page_post.tmpl.html
Labels: enhancement, ✅ Approved

#64 feat: processing worker
  AUTHORS
  Makefile
  api/sgtm.proto
  cmd/sgtm/main.go
  deployments/sgtm.club/docker-compose.yml
  gen.sum
  pkg/sgtm/opts.go
  pkg/sgtm/processing_worker.go
  pkg/sgtm/service.go
  pkg/sgtmpb/sgtm.pb.go
Labels: enhancement, 🔍 Ready for Review
